import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

export const incrementAsync = createAsyncThunk(
    'classes/fetchClass',
    async () => {
      const response = await fetch("http://localhost:8000/auth/getClasses", {
        method: "GET",
        credentials: "include",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
          "Access-Control-Allow-Credentials": true,
        },
      });
      if (response.ok) {
        return response.json();
      } else {
        return [];
      }
    }
);


export const classesSlice = createSlice({
    name: 'classes',
    // The `reducers` field lets us define reducers and generate associated actions
    initialState: {
        value: [],
        status: 'idle',
    },
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
      builder
        .addCase(incrementAsync.pending, (state) => {
          state.status = 'loading';
        })
        .addCase(incrementAsync.fulfilled, (state, action) => {
            state.status = 'idle';
            state.value = action.payload;
        })
        .addCase(incrementAsync.rejected, (state) => {
          state.status = 'failed';
        });
    },
});

export default classesSlice.reducer;